;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Doors.All",NewTagName="Doors.AllDoors")
+GameplayTagList=(Tag="Doors",DevComment="")
+GameplayTagList=(Tag="Doors.AaronRoom",DevComment="")
+GameplayTagList=(Tag="Doors.AllDoors",DevComment="")
+GameplayTagList=(Tag="Doors.Basement",DevComment="")
+GameplayTagList=(Tag="Doors.BasementVent",DevComment="")
+GameplayTagList=(Tag="Doors.Bookcase",DevComment="")
+GameplayTagList=(Tag="Doors.ElevatorDoor",DevComment="")
+GameplayTagList=(Tag="Doors.FrontDoor",DevComment="")
+GameplayTagList=(Tag="Doors.JailDoor",DevComment="")
+GameplayTagList=(Tag="Doors.LabDoor",DevComment="")
+GameplayTagList=(Tag="Doors.WorkshopRoom",DevComment="")

